version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_DB=tourdb
    ports:
      - "5432:5432"
#     volumes:
#       - postgres_data1:/var/lib/postgresql/data

# volumes:
#   postgres_data1:

  app:
    build: .
    ports:
      - "8080:8080"
#     environment:
#       - DB_HOST=db
#       - DB_PORT=5432
#       - DB_USER=postgres
#       - DB_PASSWORD=postgres
#       - DB_NAME=tournamentdb1
#     depends_on:
#       - db
#     volumes:
#       - .:/app
